export const ErrorCode = {
  AUTH: {
    NO_INVITATION: 'AUTH_NO_INVITATION',
    ACCOUNT_DEACTIVATED: 'AUTH_ACCOUNT_DEACTIVATED',
    ACCOUNT_NOT_ACTIVE: 'AUTH_ACCOUNT_NOT_ACTIVE',
    INVALID_REFRESH_TOKEN: 'AUTH_INVALID_REFRESH_TOKEN',
    NO_REFRESH_TOKEN: 'AUTH_NO_REFRESH_TOKEN',
    USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',
  },
  TEAM: {
    CONTEXT_REQUIRED: 'TEAM_CONTEXT_REQUIRED',
    NOT_A_MEMBER: 'TEAM_NOT_A_MEMBER',
    INSUFFICIENT_ROLE: 'TEAM_INSUFFICIENT_ROLE',
  },
  PROJECT: {
    NOT_FOUND: 'PROJECT_NOT_FOUND',
    CONTEXT_REQUIRED: 'PROJECT_CONTEXT_REQUIRED',
    NOT_OWNER: 'PROJECT_NOT_OWNER',
  },
  ADMIN: {
    ACCESS_REQUIRED: 'ADMIN_ACCESS_REQUIRED',
  },
} as const;
